"Leader Key
let mapleader="\<Space>"

" Basic config
set nu
syntax on
set background=dark
set smartindent
set nowrap
set showcmd
set splitright splitbelow
set tabstop=4 shiftwidth=4
set incsearch
set ignorecase
set cursorline
set wildmode=longest:full,full

set scrolloff=8
set sidescrolloff=8

set clipboard=unnamedplus
" show trailing white spaces and tabs
set listchars=tab:_\ ,trail:_
set list

" start from where you left
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" quick access vimrc
let $RC="$HOME/.vim/vimrc"

set wildmenu
set wildmode=longest,list,full

" Remaps

nnoremap ; :

nmap <silent> <C-j> <C-w>j
nmap <silent> <C-k> <C-w>k
nmap <silent> <C-l> <C-w>l
nmap <silent> <C-h> <C-w>h


inoremap jj <ESC>
inoremap JJ <ESC>
nnoremap j gj
nnoremap k gk
nnoremap <S-k> 5k
nnoremap <S-j> 5j

vnoremap < <gv
vnoremap > >gv

" Terminal remaps
nnoremap <silent> <Leader>t :term ++rows=9 ++close<cr>
tnoremap ; :
tnoremap : ;
" navigation between terminals and other panes
tmap <silent> <C-j> <C-w>j
tmap <silent> <C-k> <C-w>k
tmap <silent> <C-l> <C-w>l
tmap <silent> <C-h> <C-w>h
" hit esc for Normal mode in terminal
tmap <Esc> <C-\><C-n>

" remove | from vertsplit incicator
set fillchars+=vert:\ 

" transparent background
autocmd vimenter * hi Normal guibg=NONE ctermbg=NONE
autocmd vimenter * hi Pmenu guibg=NONE ctermbg=NONE
autocmd vimenter * hi PmenuSel guibg=NONE ctermbg=NONE

" Plugins
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin('~/.vim/plugged')

	Plugin 'morhetz/gruvbox'
	Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
	Plugin 'junegunn/fzf.vim'
	Plugin 'mhinz/vim-signify'
	Plugin 'neoclide/coc.nvim', {'branch': 'release'}
	Plugin 'tpope/vim-fugitive'
	Plugin 'tpope/vim-commentary'
	Plugin 'christoomey/vim-tmux-navigator'
	Plugin 'justinmk/vim-sneak' 	" vim sneak
	Plugin 'raimondi/delimitmate'

call vundle#end()
filetype plugin indent on

source ~/.vim/plugin/fzf/fzf.vim
source ~/.vim/plugin/signify/signify.vim
source ~/.vim/plugin/coc/coc.vim
source ~/.vim/plugin/fugitive/fugitive.vim
source ~/.vim/plugin/vim-commentary/vim-commentary.vim
source ~/.vim/plugin/vim-tmux-navigator/vim-tmux-navigator.vim
source ~/.vim/plugin/vim-sneak/vim-sneak.vim
source ~/.vim/plugin/delimitmate/delimitmate.vim
colorscheme gruvbox
