
" Install plug.vim automatically
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
      silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Basic config
set nu
syntax on
set background=dark
set smartindent
set nowrap
set showcmd
set splitright splitbelow
set tabstop=4 shiftwidth=4
set incsearch
set ignorecase
set cursorline
set wildmode=longest:full,full

set scrolloff=8
set sidescrolloff=8

set clipboard=unnamedplus
" show trailing white spaces and tabs
set listchars=tab:_\ ,trail:_
set list

" start from where you left
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" quick access vimrc
let $RC="$HOME/.vim/vimrc"


" Remaps

nnoremap ; :
nnoremap : ;
cnoremap ; :
cnoremap : ;

nmap <silent> <C-j> <C-w>j
nmap <silent> <C-k> <C-w>k
nmap <silent> <C-l> <C-w>l
nmap <silent> <C-h> <C-w>h

nnoremap j gj
nnoremap k gk
nnoremap <S-k> 5k
nnoremap <S-j> 5j

vnoremap < <gv
vnoremap > >gv
map gf :edit <cfile><cr>

" Plugins
call plug#begin('~/.vim/plugged')
	source ~/.vim/plugin/gruvbox/gruvbox.vim
	source ~/.vim/plugin/floaterm/floaterm.vim

call plug#end()
doautocmd User Plugloaded

